# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 1.9
  Include:
    - 'lib/**/*.rb'
    - 'bin/*'
    - 'Rakefile'
    - 'Gemfile'
    - '*.gemspec'
  Exclude:
    - '.**/*'
    - 'spec/**/*'
    - 'coverage/**/*'
    - '.vendor/**/*'
    - 'vendor/**/*'
    - '.bundle/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
