---
language: ruby
sudo: false
bundler_args: --without development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
cache: bundler
script:
  - bundle exec rake test
rvm:
  - '1.9'
  - '2.0'
  - '2.1'
  - '2.2'
  - '2.3'
  - '2.4'
notifications:
  email: false
